version: '3.8'

services:
  # Servicio de desarrollo con hot reload
  wsptranscriber-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wsptranscriber-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.local
    volumes:
      # Montar código fuente para hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - wsptranscriber-network
    command: npm run dev

networks:
  wsptranscriber-network:
    driver: bridge
