
services:
  # Aplicación principal WSP Transcriber
  wsptranscriber:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wsptranscriber-app
    # Solo exponer puerto interno para Caddy (no público)
    expose:
      - "3000"
    # Para acceso directo sin Caddy, descomenta la siguiente línea:
    # ports:
    #   - "80:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # Variables para proxy reverso
      - HOSTNAME=0.0.0.0
      - PORT=3000
    env_file:
      - .env.local
    volumes:
      # Volumen para archivos temporales de uploads
      - uploads:/app/uploads
      # Volumen para logs (opcional)
      - logs:/app/logs
    restart: unless-stopped
    networks:
      - caddy-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Caddy como proxy reverso
  caddy:
    image: caddy:2-alpine
    container_name: wsptranscriber-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CADDY_INGRESS_NETWORKS=caddy-network
    networks:
      - caddy-network
    restart: unless-stopped
    depends_on:
      - wsptranscriber

  # Servicio de desarrollo (comentado por defecto)
  # wsptranscriber-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: wsptranscriber-dev
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - NODE_ENV=development
  #   env_file:
  #     - .env.local
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/.next
  #   command: npm run dev
  #   networks:
  #     - wsptranscriber-network

volumes:
  uploads:
    driver: local
  logs:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local

networks:
  caddy-network:
    driver: bridge
    name: caddy-network
